 # Table of Contents
<div class="toc" style="margin-top: 1em;"><ul class="toc-item" id="toc-level0"><ul class="toc-item"><li><span><a href="http://localhost:8913/notebooks/char-Mekdes_copy.ipynb#Solution-to-Characteristic-Equation" data-toc-modified-id="Solution-to-Characteristic-Equation-0.1"><span class="toc-item-num">0.1&nbsp;&nbsp;</span>Solution to Characteristic Equation</a></span></li></ul></ul></div>

# Table of Contents


## Solution to Characteristic Equation


Given
$$B = \begin{bmatrix} 
       3 & 2 & 4\\
       2 & 0 & 2 \\
       4 & 2 & 3
       \end{bmatrix}$$

Substituting the matrix into the characteristic equation:


$$0 = \det \left (\begin{bmatrix} 
    \vphantom{1}3 & 2 & 4\\
       2 & 0 & 2 \vphantom{1}\\ 4 & 2 & 3
       \end{bmatrix} - \lambda \begin{bmatrix} 
       1 & 0 & 0\\
       0 & 1 & 0 \\
       0 & 0 & 1
       \end{bmatrix}\right) = 0 $$

$$ = \det \begin{bmatrix} 
       3-\lambda & 2 & 4\\
       2 & -\lambda & 2 \\
       4 & 2 & 3-\lambda
       \end{bmatrix} $$
       
$$ = (3-\lambda)[(-\lambda)(3-\lambda)-4] - 2[(2)(3-\lambda)-8] + 4[4+4\lambda]$$ 

$$ = \lambda ^{3} - 6\lambda ^2 - 15\lambda + 8$$

$$ = (\lambda -8)(\lambda +1)^2$$

$$ \implies  \lambda = -1 \quad \text{or} \quad 8$$

The eigenvalues of **B** are -1 and 8.

Check this answer with python.

In [9]:
import numpy as np
B = np.matrix([[3, 2, 4], [2 ,0 ,2],[4,2,3]])
eigval, eigvec = np.linalg.eig(B)
print(f'eigenvectors: \n{eigvec[:,0]}\n{eigvec[:,1]}\n{eigvec[:,2]}')
print(f'eigenvalues: {eigval}')

eigenvectors: 
[[-0.74535599]
 [ 0.2981424 ]
 [ 0.59628479]]
[[ 0.66666667]
 [ 0.33333333]
 [ 0.66666667]]
[[-0.20756326]
 [-0.77602137]
 [ 0.59557394]]
eigenvalues: [-1.  8. -1.]


John M. Stockie

Fri Sep 8 14:03:35 PDT 2017